SET FOREIGN_KEY_CHECKS=0; 
drop table if exists entity ;
drop table if exists entity_instance ;
drop table if exists item;
drop table if exists item_instance;
drop table if exists block;
drop table if exists block_instance ;
drop table if exists chunk ;
drop table if exists biome ;
drop table if exists biome_blocks;
drop table if exists structure;
drop table if exists enchantment;
drop table if exists inventory;
drop table if exists player;
drop table if exists mob;
drop table if exists armor_stand;
drop table if exists minecart;
drop table if exists block_drops;
drop table if exists creates_block;
drop table if exists creates_entity;
drop table if exists entity_drops;
drop table if exists structure_made_of;
SET FOREIGN_KEY_CHECKS=1; 